redis:
  image: redis
  command: redis-server --appendonly yes
  ports:
    - 6379:6379

mongodb:
  image: mongo
  ports:
    - 27017:27017

doc-worker:
  dockerfile: ./doc-worker.docker
  build: ./
  links:
    - redis
    - mongodb
  environment:
    - NODE_ENV=dev
  env_file: ./secrets.env

api-server:
  dockerfile: ./api-server.docker
  build: ./
  links:
    - redis
  ports:
    - 3420:3420
  environment:
    - NODE_ENV=dev
  env_file: ./secrets.env

web-server:
  dockerfile: ./web-server.docker
  build: ./
  links:
    - mongodb
    - redis
  ports:
    - 8030:8080
  restart: always
  environment:
    - NODE_ENV=dev
  env_file: ./secrets.env

  


